language: r
r:
  - release
#  - devel

latex: true
warnings_are_errors: TRUE

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

cache:
  - packages
  - ccache

r_binary_packages:
  - rlang
  - tidyr
  - dplyr

r_packages:
  - remotes

r_github_packages:
  - jimhester/lintr
  - r-lib/covr

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
