# documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: true
dist: trusty
cache: packages
latex: true
warnings_are_errors: true

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

#r_check_args: "--run-dontrun"



notifications:
  email:
  on_success: change
  on_failure: change

matrix:
  include:
    - os: linux
      dist: trusty
      r:
        - release
        - devel
      r_packages:
        - rlang
        - tidyr
        - dplyr
        - remotes
      r_github_packages:
        - jimhester/lintr
        - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
