# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
latex: false
fortran: true

# Note: http test servers are flaky and we want to minimze false positives
# so we skip examples and vignettes (but not unit tests) on OS X.

matrix:
  include:
#   precise is getting decommissioned on Travis, so better to leave it out
    - os: linux
      dist: trusty
      sudo: false
      env: R_CODECOV = true
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode7.3
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

r_packages:
  - covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
