codecov:
  token: 21c926be-663e-46e8-a3a6-5664230f0d26
  branch: master

coverage:
  precision: 3
  round: nearest
  range: "50...100"

  status:
    project:
      default:
        target: auto
        branches: null
        threshold: 5%
        informational: true

    patch:
      default:
        target: auto
        branches: null
        threshold: 5%
        informational: true

    changes:
      default:
        branches: null
        threshold: 5%
        informational: true

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
